---
- name: Install block
  block:
    - name: update apt cache
      apt:
        update_cache: True
      tags:
        - install
    - name: install apt packages
      apt:
        name:
          - htop
          - btop
          - xz-utils
          - rsync
        state: present
      tags:
        - install
    - name: setup factorio user
      user:
        name: "{{ factorio_user }}"
        shell: /bin/bash
        create_home: True
        state: present
      tags:
        - install
    - name: generate systemd file for factorio
      template:
        src: systemd/factorio.service.j2
        dest: /etc/systemd/system/factorio.service
        owner: root
        group: root
        mode: 0644
      tags:
        - install
      notify:
        - systemd reload
        - factorio restart
    - name: download factorio headless server
      get_url:
        url: "{{ factorio_headless_server }}"
        dest: "/home/{{ factorio_user }}/factorio_headless.tar.xz"
      tags:
        - install
        - factorio
    - name: uncompress factorio server file
      unarchive:
        remote_src: True
        src: "/home/{{ factorio_user }}/factorio_headless.tar.xz"
        dest: "/home/{{ factorio_user }}"
        creates: "{{ factorio_root }}"
      tags:
        - install
        - factorio
    - name: copy factorio save file to host
      copy:
        src: "{{ factorio_save_location }}"
        dest: "{{ factorio_root }}"
      tags:
        - install
        - factorio
      when: factorio_save_location is defined
      notify:
        - factorio restart
    - name: generate factorio config.ini
      copy:
        dest: "{{ factorio_server_settings_file }}"
        content: "{{ factorio_server_settings }}"
      tags:
        - install
        - factorio
      notify:
        - factorio restart
    - name: create mods directory
      file:
        path: "{{ factorio_root }}/mods"
        state: directory
      tags:
        - install
        - factorio
    - name: generate list of mods enabled
      set_fact:
        factorio_mods: "{{ lookup('file', '{{ factorio_mods_location }}/{{ factorio_mods_list }}') | from_json }}"
      tags:
        - install
        - factorio
    - name: find all mod files and save their paths
      debug:
        msg: "{{ lookup('fileglob', '{{ factorio_mods_location }}/{{ item.name }}_*.zip', wantlist=True) }}"
      when: item.enabled is true
      register: factorio_mods_path
      loop: "{{ factorio_mods.mods }}"
      tags:
        - install
        - factorio
    - name: copy mod files over to host
      copy:
        src: "{{ item.msg[0] }}"
        dest: "{{ factorio_root }}/mods/"
      when: item.msg is defined and item.msg | length > 0
      loop: "{{ factorio_mods_path.results | select() }}"
      tags:
        - install
        - factorio
    - name: generate mod-lists.json
      copy:
        dest: "{{ factorio_root }}/mods/{{ factorio_mods_list }}"
        content: "{{ factorio_mods }}"
      tags:
        - install
        - factorio
    - name: ensure that permissions are correct
      file:
        path: "{{ factorio_root }}"
        state: directory
        owner: "{{ factorio_user }}"
        group: "{{ factorio_user }}"
        recurse: True
      tags:
        - install
        - factorio
  tags:
    - never
    - install
    - factorio
