---
- name: spawn variables
  set_fact:
    sshkeys_list: []
  tags:
    - deploy

- name: gather sshkey info from digital ocean
  digital_ocean_sshkey_info:
  register: sshkeys
  tags:
    - deploy

- name: generate sshkeys ids
  set_fact:
    sshkeys_list: "{{ sshkeys_list + [ item.id ] }}"
  loop: "{{ sshkeys.data }}"
  tags:
    - deploy

- name: create droplet
  digital_ocean_droplet:
    state: present
    ssh_keys: "{{ sshkeys_list }}"
  args: "{{ droplet }}"
  connection: local
  tags:
    - deploy
  register: droplet_out
